### ISSUE TITLE
Suggestion to Revert or Modify the Glyph for 翁

### ISSUE THREAD

**Issue by pan-asian-wok** [tamcy/chiron-sans-hk#1]
Thank you for providing this beautiful font! I did noticed though that the top and bottom components of the glyph for 翁 do not match the aesthetics of other similar characters. Below are some examples:

![Similar Characters to 翁 (version 2)](https://user-images.githubusercontent.com/45274474/62002689-7d68fb00-b0d7-11e9-81e7-662135128aa2.png)

I just wanted to bring this to your attention for possible reverting or modifying if you so choose to.

**Comment by tamcy** [comment]
Thank you for your report. The codepoint U+7FC1 翁 was incorrectly remapped to the KR glyph when it should've been left as-is. This will be fixed in the next release.
