### ISSUE TITLE
腩's radical

### ISSUE THREAD

**Issue by Raymonf** [tamcy/chiron-sans-hk#4]
The 腩 glyph seems to be the TW glyph. I think the CN glyph may fit better. Thoughts?

**Comment by tamcy** [comment]
Thank you for your comment. You are correct that the TW glyph is chosen for U+8169 腩. There are two differences between the CN and TW/HK glyphs:

![uni8169](https://user-images.githubusercontent.com/959433/72249653-c0db0580-3634-11ea-9503-a42d6750494b.png)

(1) the radical - ⿰月 (CN) vs ⿰⺼ (TW/HK);
(2) the second stroke of 南 - slightly slanted (CN) vs vertical (TW/HK)

Chiron Sans HK prefers the TW/HK form for these two features. You can see similar characters in Big5/HKSCS like 腳, 脫, 腹, 脂, 肺 etc. are all in ⿰⺼.

**Comment by Raymonf** [comment]
Ah, you're right. It does make sense that it be 肉部, too. Thank you for the explanation and sorry for the troubles!
