### ISSUE TITLE
希望有歐文等寬字體的版本

### ISSUE THREAD

**Issue by chlbc** [tamcy/chiron-sans-hk#5]
首先感謝作者的分享！！很喜歡這個版本的字形！！

這邊想請問作者大大一個問題：請問作者會做歐文是等寬字體、類似思源等寬的版本嗎？想在寫程式時使用這個字型。

**Comment by tamcy** [comment]
謝謝讚賞！坦白說，我並無製作歐文等寬字體的打算。

首先，我慣用的 IDE 容許設定主字體和 fallback 字體，所以自己沒有在一套字體中包含西文等寬＋中文字形的需要。

另外，本來昭源黑體的想用 Noto Sans 取代原來思源的西文字體，但由於成效不佳、有若干問題，於是放棄，並專注在中文字的調整上。但這個概念其實一直沒有消失，我一直希望能將兩者（或另一套西文字體）整合，成事後用另一個名稱發表，只是時間所限，進展緩慢。換言之，我還有一款自己想做的字體，雖然是否、何時推出仍然未知。

最後，我一直希望待思源宋體 2.0 版發佈後製作一款方針與昭源黑體類近、以思源宋體為基礎的宋體字型（也就是昭源宋體），而順利的話思源宋體 2.0 版應該會在今年推出（雖然最近 Adobe 的人事變動不知道對這個有沒有影響）。

由於種種原因，在有限的時間下，請容我自私一點，先照顧自己的「野心」。謝謝。
