### ISSUE TITLE
=|=　部件

### ISSUE THREAD

**Issue by lapomme** [tamcy/chiron-sans-hk#7]
為什麼「屬、遲」等字的「氺」沒有統一改爲「=|=」？

![image](https://user-images.githubusercontent.com/27000939/84572941-7f798e00-ad6b-11ea-81cf-d5e90b1201b3.png)

**Comment by tamcy** [comment]
這個問題我在製作時也考慮過一陣子。要考慮的原因是不同「⻗」，屬/犀那個「類氺」部件作橫還是作點我也可以接受。最後選擇不動原因是：

1. 兩款部件雖然都有一個「類氺」狀，但「雨」字的四點跟「犀（減牛）」那個部件本身沒有甚麼關連（「雨」的結構也不是「丨」加四點而是「帀」加四點），所以不見得寫法必須相同。
2. 「雨」字中間本來也不算是四個橫筆：它單獨使用時作四「丶」，在上方時可以理解為「被壓扁」才變成「一」。就算「屬遲雲」變成四橫，「屬遲雨」仍是不同。
3. 這個決定跟蒙納黑/宋體的做法相同。
4. 減少重繪字形數。

雖然將屬/犀類字改成四橫我覺得也無不可（到時會有 12 個字沒有可用字形，至少有 6 個應該重繪），但若真要說「統一」，事實上連「脊」系列字也應該一併改成橫筆。這我個人不是太願意。

順帶一提，華康儷黑「⻗、犀」作橫，「脊」作點。華康儷宋則「⻗、犀、脊」均作橫。而華康和蒙納的仿宋體都是「⻗」作橫而「犀、脊」作點。

**Comment by tamcy** [comment]
犀、犀、皐、臯、褱 中間象「氺」狀部件在 2.027 版會改為橫筆。
